# Generated by Django 4.0 on 2022-08-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_monitor_retry_interval_monitor_timeout_monitor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='options',
            field=models.JSONField(blank=True, null=True, verbose_name='Options'),
        ),
    ]
