# Generated by Django 4.0 on 2022-08-18 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_monitor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hostname'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='port',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(0)], verbose_name='Interval'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
